In [2]:
import numpy as np

1/ Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [4]:
a = np.arange(1, 11, 1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2/ Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [5]:
b = np.zeros((3,3))
print (b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3/ Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [7]:
c = np.random.randint(1,10, (5,5))
print(c)

[[6 7 9 9 2]
 [3 8 7 1 7]
 [6 3 8 6 4]
 [7 6 8 1 5]
 [6 3 2 7 9]]


4/ Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [8]:
d = np.random.rand(4,4)
print(d)

[[0.27137292 0.77127954 0.53350462 0.67111588]
 [0.10111046 0.12931056 0.39397114 0.2051007 ]
 [0.6728756  0.44734021 0.90841316 0.22580696]
 [0.9891682  0.57386798 0.26143992 0.2900479 ]]


5/Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення

In [13]:
e = np.random.randint(1,10, (1,5))
f = np.random.randint(1,10, (1,5))
print(e)
print(f)
print(f"поелементне додавання: {e+f}")
print(f"поелементне віднімання: {e-f}")
print(f"поелементне множення: {e*f}")

[[1 3 4 5 9]]
[[2 4 1 1 8]]
поелементне додавання: [[ 3  7  5  6 17]]
поелементне віднімання: [[-1 -1  3  4  1]]
поелементне множення: [[ 2 12  4  5 72]]


6/ Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [16]:
e = np.array([1,2,3,4,5,6,7])
f = np.array([2,1,3,4,5,1,2])
print (e)
print(f)
print(f"скалярний добуток: {np.dot(e,f)}")

[1 2 3 4 5 6 7]
[2 1 3 4 5 1 2]
скалярний добуток: 74


7/Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [20]:
A = np.random.randint(1,10, (2,2))
B = np.random.randint(1,10, (2,3))
print(A)
print(B)
print(f"матричний добуток: {np.dot(A,B)}")

[[3 9]
 [8 9]]
[[2 9 2]
 [4 7 4]]
матричний добуток: [[ 42  90  42]
 [ 52 135  52]]


8/ Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [24]:
A = np.random.randint(1,10, (3,3))
print(A)
print(f"обернена матриця: {np.linalg.inv(A)}")

[[9 5 6]
 [9 9 2]
 [6 2 7]]
обернена матриця: [[ 0.98333333 -0.38333333 -0.73333333]
 [-0.85        0.45        0.6       ]
 [-0.6         0.2         0.6       ]]


9/ Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її

In [27]:
A = np.random.random((4,4))
print(A)
B = A.T
print(f"транспонована матриця: {B}")

[[0.49107463 0.51445524 0.87974402 0.98415902]
 [0.75254164 0.87704374 0.04453121 0.89168495]
 [0.40214499 0.87981392 0.90965739 0.79924935]
 [0.58216839 0.45699448 0.11857467 0.85930065]]
транспонована матриця: [[0.49107463 0.75254164 0.40214499 0.58216839]
 [0.51445524 0.87704374 0.87981392 0.45699448]
 [0.87974402 0.04453121 0.90965739 0.11857467]
 [0.98415902 0.89168495 0.79924935 0.85930065]]


10/ Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [31]:
A = np.random.randint(1,10, (3,4))
print(A)
B = np.random.randint(1,10, (1,4))
print(B)
print(f"поелементне множення: {A*B}")


[[1 8 8 2]
 [5 5 5 6]
 [5 2 8 6]]
[[1 9 1 9]]
поелементне множення: [[ 1 72  8 18]
 [ 5 45  5 54]
 [ 5 18  8 54]]


11/ Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [35]:
A = np.random.random((2,3))
print(A)
B = np.random.random((3,1))
print(B)
print(f"множення: {np.dot(A,B)}")


[[0.94259883 0.90371152 0.66162931]
 [0.9591207  0.84946383 0.4406238 ]]
[[0.04186604]
 [0.38273089]
 [0.80121943]]
множення: [[0.91545145]
 [0.71830698]]


12/ Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [36]:
a = np.random.randint(1,10, (2,2))
print(a)
b = np.random.randint(1,10, (2,2))
print(b)
print(f"поелементне множення: {a*b}")


[[7 5]
 [6 8]]
[[1 1]
 [7 3]]
поелементне множення: [[ 7  5]
 [42 24]]


13/ Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [57]:
a = np.random.randint(1,10, (2,2))
print(a)
b = np.random.randint(1,10, (2,2))
print(b)
print(f"добуток: {np.dot(a,b)}")

[[2 5]
 [6 8]]
[[3 8]
 [8 7]]
добуток: [[ 46  51]
 [ 82 104]]


14/ Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці

In [56]:
a = np.random.randint(1,100, (5,5))
print(a)
b = a.sum()
print(b)

[[13 87 20 98 12]
 [77 24  7 26 45]
 [56 79 37 50 66]
 [63 55 16 88 31]
 [ 9 16 59 86 15]]
1135


15/Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю

In [55]:
a = np.random.randint(1,10, (4,4))
print(a)
b = np.random.randint(1,10, (4,4))
print(b)
print(f"різниця: {(a-b)}")

[[6 7 6 1]
 [4 3 2 1]
 [8 7 4 9]
 [4 4 8 9]]
[[1 2 6 9]
 [9 1 6 3]
 [1 2 4 7]
 [4 9 7 2]]
різниця: [[ 5  5  0 -8]
 [-5  2 -4 -2]
 [ 7  5  0  2]
 [ 0 -5  1  7]]


16/ Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [54]:
a = np.random.random((3,3))
print(a)
B = np.sum(a, 1)
print (b)

[[0.90343727 0.35550902 0.57047191]
 [0.87575613 0.1428745  0.8667588 ]
 [0.48088654 0.4640955  0.91345244]]
[[1 4 0 1]
 [1 4 9 9]
 [1 4 9 4]]


17/ Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел

In [53]:
a = np.array([[1,2,0,1], [1,2,3,3],[1,2,3,2]])
print(a)
b = np.power(a,2)
print(b)

[[1 2 0 1]
 [1 2 3 3]
 [1 2 3 2]]
[[1 4 0 1]
 [1 4 9 9]
 [1 4 9 4]]


18/ Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [58]:
a = np.random.randint(1,50, (4))
print(a)
b = np.sqrt(a)
print(b)

[13 12  9 19]
[3.60555128 3.46410162 3.         4.35889894]
